
client_id = "2dcad119d4be69267ea46c2c519d3e7e"
name = "TrackMe"
application_url = "https://timocetrackme.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,read_orders,write_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [
  "https://timocetrackme.onrender.com/auth/callback",
  "https://timocetrackme.onrender.com/auth/shopify/callback",
  "https://timocetrackme.onrender.com/api/auth/callback"
]
